### ISSUE TITLE
jsonpatch missing from recipe

### ISSUE THREAD

**Issue by chambbj** [conda-forge/visdom-feedstock#13]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

It appears as though the `visdom` install should actually include `jsonpatch` as a runtime requirement. Is there a reason this is deliberately omitted from https://github.com/conda-forge/visdom-feedstock/blob/master/recipe/meta.yaml?

```
$ visdom
Traceback (most recent call last):
  File "/home/chambbj/miniconda3/envs/conda-build/envs/visdom-ticket/bin/visdom", line 8, in <module>
    from visdom.server import download_scripts_and_run
  File "/home/chambbj/miniconda3/envs/conda-build/envs/visdom-ticket/lib/python3.10/site-packages/visdom/server.py", line 20, in <module>
    import jsonpatch
ModuleNotFoundError: No module named 'jsonpatch'
```

Installing `jsonpatch` on top of this environment seems to resolve the issue.

```
$ conda install -c conda-forge jsonpatch
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/chambbj/miniconda3/envs/conda-build/envs/visdom-ticket

  added / updated specs:
    - jsonpatch


The following NEW packages will be INSTALLED:

  jsonpatch          conda-forge/noarch::jsonpatch-1.32-pyhd8ed1ab_0
  jsonpointer        conda-forge/noarch::jsonpointer-2.0-py_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ visdom
Checking for scripts.
Downloading scripts, this may take a little while
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/chambbj/miniconda3/envs/conda-build/envs/visdom-ticket:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.8              pyhd8ed1ab_0    conda-forge
cryptography              36.0.0                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.21.4                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.0          h62f1059_3_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyzmq                     22.3.0                   pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
scipy                     1.7.3                    pypi_0    pypi
setuptools                59.4.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
torchfile                 0.1.0                      py_0    conda-forge
tornado                   6.1                      pypi_0    pypi
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
visdom                    0.1.8.9                       0    conda-forge
websocket-client          1.2.1                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : visdom-ticket
    active env location : /home/chambbj/miniconda3/envs/conda-build/envs/visdom-ticket
            shell level : 2
       user config file : /home/chambbj/.condarc
 populated config files : /home/chambbj/.condarc
          conda version : 4.10.3
    conda-build version : 3.19.0
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/chambbj/miniconda3/envs/conda-build  (writable)
      conda av data dir : /home/chambbj/miniconda3/envs/conda-build/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/chambbj/miniconda3/envs/conda-build/pkgs
                          /home/chambbj/.conda/pkgs
       envs directories : /home/chambbj/miniconda3/envs/conda-build/envs
                          /home/chambbj/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.7.10 Linux/5.4.0-90-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by da-h** [comment]
Should be solved as of #17.
